workflows:
  my-workflow:
    environment:
      groups:
        - serverconfig
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Run tests
        script: npm run testverbose
    publishing:
      email:
        recipients:
          - $emailaddress
    triggering:
      events:                       # List the events that trigger builds
        - push
      cancel_previous_builds: false        

